### ISSUE TITLE
验证码

### ISSUE THREAD

**Issue by yonj1e** [hohoTT/Logistics_Manage_System#6]
登录注册时验证码显示不出来，几个主流浏览器都试了。

**Comment by hohoTT** [comment]
问题在于你的JavaBuildPath配置存在问题，项目导入之后要先查看一下该项目的JavaBuildPath配置，确保Tomcat、jdk这一些依赖可以被项目正确依赖使用
[JavaBuildPath配置](https://raw.githubusercontent.com/hohoTT/Logistics_Manage_System/master/img/librariesSetting.jpg)
